package com.dyz.myBatis.dao;

import java.util.Date;

import com.dyz.myBatis.model.Roominfo;
import com.dyz.myBatis.model.RoominfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoominfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int countByExample(RoominfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int deleteByExample(RoominfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int insert(Roominfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int insertSelective(Roominfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	List<Roominfo> selectByExample(RoominfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	Roominfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Roominfo record,
			@Param("example") RoominfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Roominfo record,
			@Param("example") RoominfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Roominfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Roominfo record);

	Roominfo selectRoomId(Integer roomid);
    
    int selectCount();
    
    int selectTodayCount(Date date);
}