package com.dyz.myBatis.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class AccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public AccountExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUuidIsNull() {
			addCriterion("uuid is null");
			return (Criteria) this;
		}

		public Criteria andUuidIsNotNull() {
			addCriterion("uuid is not null");
			return (Criteria) this;
		}

		public Criteria andUuidEqualTo(Integer value) {
			addCriterion("uuid =", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotEqualTo(Integer value) {
			addCriterion("uuid <>", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThan(Integer value) {
			addCriterion("uuid >", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uuid >=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThan(Integer value) {
			addCriterion("uuid <", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThanOrEqualTo(Integer value) {
			addCriterion("uuid <=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidIn(List<Integer> values) {
			addCriterion("uuid in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotIn(List<Integer> values) {
			addCriterion("uuid not in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidBetween(Integer value1, Integer value2) {
			addCriterion("uuid between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotBetween(Integer value1, Integer value2) {
			addCriterion("uuid not between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNull() {
			addCriterion("openid is null");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNotNull() {
			addCriterion("openid is not null");
			return (Criteria) this;
		}

		public Criteria andOpenidEqualTo(String value) {
			addCriterion("openid =", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotEqualTo(String value) {
			addCriterion("openid <>", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThan(String value) {
			addCriterion("openid >", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThanOrEqualTo(String value) {
			addCriterion("openid >=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThan(String value) {
			addCriterion("openid <", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThanOrEqualTo(String value) {
			addCriterion("openid <=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLike(String value) {
			addCriterion("openid like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotLike(String value) {
			addCriterion("openid not like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidIn(List<String> values) {
			addCriterion("openid in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotIn(List<String> values) {
			addCriterion("openid not in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidBetween(String value1, String value2) {
			addCriterion("openid between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotBetween(String value1, String value2) {
			addCriterion("openid not between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickName is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickName is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickName =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickName <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickName >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickName >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickName <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickName <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickName like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickName not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickName in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickName not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickName between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickName not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andHeadiconIsNull() {
			addCriterion("headIcon is null");
			return (Criteria) this;
		}

		public Criteria andHeadiconIsNotNull() {
			addCriterion("headIcon is not null");
			return (Criteria) this;
		}

		public Criteria andHeadiconEqualTo(String value) {
			addCriterion("headIcon =", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconNotEqualTo(String value) {
			addCriterion("headIcon <>", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconGreaterThan(String value) {
			addCriterion("headIcon >", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconGreaterThanOrEqualTo(String value) {
			addCriterion("headIcon >=", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconLessThan(String value) {
			addCriterion("headIcon <", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconLessThanOrEqualTo(String value) {
			addCriterion("headIcon <=", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconLike(String value) {
			addCriterion("headIcon like", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconNotLike(String value) {
			addCriterion("headIcon not like", value, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconIn(List<String> values) {
			addCriterion("headIcon in", values, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconNotIn(List<String> values) {
			addCriterion("headIcon not in", values, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconBetween(String value1, String value2) {
			addCriterion("headIcon between", value1, value2, "headicon");
			return (Criteria) this;
		}

		public Criteria andHeadiconNotBetween(String value1, String value2) {
			addCriterion("headIcon not between", value1, value2, "headicon");
			return (Criteria) this;
		}

		public Criteria andRoomcardIsNull() {
			addCriterion("roomCard is null");
			return (Criteria) this;
		}

		public Criteria andRoomcardIsNotNull() {
			addCriterion("roomCard is not null");
			return (Criteria) this;
		}

		public Criteria andRoomcardEqualTo(Integer value) {
			addCriterion("roomCard =", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardNotEqualTo(Integer value) {
			addCriterion("roomCard <>", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardGreaterThan(Integer value) {
			addCriterion("roomCard >", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardGreaterThanOrEqualTo(Integer value) {
			addCriterion("roomCard >=", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardLessThan(Integer value) {
			addCriterion("roomCard <", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardLessThanOrEqualTo(Integer value) {
			addCriterion("roomCard <=", value, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardIn(List<Integer> values) {
			addCriterion("roomCard in", values, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardNotIn(List<Integer> values) {
			addCriterion("roomCard not in", values, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardBetween(Integer value1, Integer value2) {
			addCriterion("roomCard between", value1, value2, "roomcard");
			return (Criteria) this;
		}

		public Criteria andRoomcardNotBetween(Integer value1, Integer value2) {
			addCriterion("roomCard not between", value1, value2, "roomcard");
			return (Criteria) this;
		}

		public Criteria andUnionidIsNull() {
			addCriterion("unionid is null");
			return (Criteria) this;
		}

		public Criteria andUnionidIsNotNull() {
			addCriterion("unionid is not null");
			return (Criteria) this;
		}

		public Criteria andUnionidEqualTo(String value) {
			addCriterion("unionid =", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidNotEqualTo(String value) {
			addCriterion("unionid <>", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidGreaterThan(String value) {
			addCriterion("unionid >", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidGreaterThanOrEqualTo(String value) {
			addCriterion("unionid >=", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidLessThan(String value) {
			addCriterion("unionid <", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidLessThanOrEqualTo(String value) {
			addCriterion("unionid <=", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidLike(String value) {
			addCriterion("unionid like", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidNotLike(String value) {
			addCriterion("unionid not like", value, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidIn(List<String> values) {
			addCriterion("unionid in", values, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidNotIn(List<String> values) {
			addCriterion("unionid not in", values, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidBetween(String value1, String value2) {
			addCriterion("unionid between", value1, value2, "unionid");
			return (Criteria) this;
		}

		public Criteria andUnionidNotBetween(String value1, String value2) {
			addCriterion("unionid not between", value1, value2, "unionid");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceIn(List<String> values) {
			addCriterion("province in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotIn(List<String> values) {
			addCriterion("province not in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andPrizecountIsNull() {
			addCriterion("prizecount is null");
			return (Criteria) this;
		}

		public Criteria andPrizecountIsNotNull() {
			addCriterion("prizecount is not null");
			return (Criteria) this;
		}

		public Criteria andPrizecountEqualTo(Integer value) {
			addCriterion("prizecount =", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountNotEqualTo(Integer value) {
			addCriterion("prizecount <>", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountGreaterThan(Integer value) {
			addCriterion("prizecount >", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountGreaterThanOrEqualTo(Integer value) {
			addCriterion("prizecount >=", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountLessThan(Integer value) {
			addCriterion("prizecount <", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountLessThanOrEqualTo(Integer value) {
			addCriterion("prizecount <=", value, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountIn(List<Integer> values) {
			addCriterion("prizecount in", values, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountNotIn(List<Integer> values) {
			addCriterion("prizecount not in", values, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountBetween(Integer value1, Integer value2) {
			addCriterion("prizecount between", value1, value2, "prizecount");
			return (Criteria) this;
		}

		public Criteria andPrizecountNotBetween(Integer value1, Integer value2) {
			addCriterion("prizecount not between", value1, value2, "prizecount");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdIsNull() {
			addCriterion("manager_up_id is null");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdIsNotNull() {
			addCriterion("manager_up_id is not null");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdEqualTo(Integer value) {
			addCriterion("manager_up_id =", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdNotEqualTo(Integer value) {
			addCriterion("manager_up_id <>", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdGreaterThan(Integer value) {
			addCriterion("manager_up_id >", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("manager_up_id >=", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdLessThan(Integer value) {
			addCriterion("manager_up_id <", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdLessThanOrEqualTo(Integer value) {
			addCriterion("manager_up_id <=", value, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdIn(List<Integer> values) {
			addCriterion("manager_up_id in", values, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdNotIn(List<Integer> values) {
			addCriterion("manager_up_id not in", values, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdBetween(Integer value1, Integer value2) {
			addCriterion("manager_up_id between", value1, value2, "managerUpId");
			return (Criteria) this;
		}

		public Criteria andManagerUpIdNotBetween(Integer value1, Integer value2) {
			addCriterion("manager_up_id not between", value1, value2,
					"managerUpId");
			return (Criteria) this;
		}

		public Criteria andActualcardIsNull() {
			addCriterion("actualCard is null");
			return (Criteria) this;
		}

		public Criteria andActualcardIsNotNull() {
			addCriterion("actualCard is not null");
			return (Criteria) this;
		}

		public Criteria andActualcardEqualTo(Integer value) {
			addCriterion("actualCard =", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardNotEqualTo(Integer value) {
			addCriterion("actualCard <>", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardGreaterThan(Integer value) {
			addCriterion("actualCard >", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardGreaterThanOrEqualTo(Integer value) {
			addCriterion("actualCard >=", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardLessThan(Integer value) {
			addCriterion("actualCard <", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardLessThanOrEqualTo(Integer value) {
			addCriterion("actualCard <=", value, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardIn(List<Integer> values) {
			addCriterion("actualCard in", values, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardNotIn(List<Integer> values) {
			addCriterion("actualCard not in", values, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardBetween(Integer value1, Integer value2) {
			addCriterion("actualCard between", value1, value2, "actualcard");
			return (Criteria) this;
		}

		public Criteria andActualcardNotBetween(Integer value1, Integer value2) {
			addCriterion("actualCard not between", value1, value2, "actualcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardIsNull() {
			addCriterion("totalCard is null");
			return (Criteria) this;
		}

		public Criteria andTotalcardIsNotNull() {
			addCriterion("totalCard is not null");
			return (Criteria) this;
		}

		public Criteria andTotalcardEqualTo(Integer value) {
			addCriterion("totalCard =", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardNotEqualTo(Integer value) {
			addCriterion("totalCard <>", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardGreaterThan(Integer value) {
			addCriterion("totalCard >", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardGreaterThanOrEqualTo(Integer value) {
			addCriterion("totalCard >=", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardLessThan(Integer value) {
			addCriterion("totalCard <", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardLessThanOrEqualTo(Integer value) {
			addCriterion("totalCard <=", value, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardIn(List<Integer> values) {
			addCriterion("totalCard in", values, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardNotIn(List<Integer> values) {
			addCriterion("totalCard not in", values, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardBetween(Integer value1, Integer value2) {
			addCriterion("totalCard between", value1, value2, "totalcard");
			return (Criteria) this;
		}

		public Criteria andTotalcardNotBetween(Integer value1, Integer value2) {
			addCriterion("totalCard not between", value1, value2, "totalcard");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNull() {
			addCriterion("lastLoginTime is null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNotNull() {
			addCriterion("lastLoginTime is not null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeEqualTo(Date value) {
			addCriterion("lastLoginTime =", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotEqualTo(Date value) {
			addCriterion("lastLoginTime <>", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThan(Date value) {
			addCriterion("lastLoginTime >", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lastLoginTime >=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThan(Date value) {
			addCriterion("lastLoginTime <", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThanOrEqualTo(Date value) {
			addCriterion("lastLoginTime <=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIn(List<Date> values) {
			addCriterion("lastLoginTime in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotIn(List<Date> values) {
			addCriterion("lastLoginTime not in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeBetween(Date value1, Date value2) {
			addCriterion("lastLoginTime between", value1, value2,
					"lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotBetween(Date value1, Date value2) {
			addCriterion("lastLoginTime not between", value1, value2,
					"lastlogintime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andIsgameIsNull() {
			addCriterion("isGame is null");
			return (Criteria) this;
		}

		public Criteria andIsgameIsNotNull() {
			addCriterion("isGame is not null");
			return (Criteria) this;
		}

		public Criteria andIsgameEqualTo(String value) {
			addCriterion("isGame =", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameNotEqualTo(String value) {
			addCriterion("isGame <>", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameGreaterThan(String value) {
			addCriterion("isGame >", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameGreaterThanOrEqualTo(String value) {
			addCriterion("isGame >=", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameLessThan(String value) {
			addCriterion("isGame <", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameLessThanOrEqualTo(String value) {
			addCriterion("isGame <=", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameLike(String value) {
			addCriterion("isGame like", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameNotLike(String value) {
			addCriterion("isGame not like", value, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameIn(List<String> values) {
			addCriterion("isGame in", values, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameNotIn(List<String> values) {
			addCriterion("isGame not in", values, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameBetween(String value1, String value2) {
			addCriterion("isGame between", value1, value2, "isgame");
			return (Criteria) this;
		}

		public Criteria andIsgameNotBetween(String value1, String value2) {
			addCriterion("isGame not between", value1, value2, "isgame");
			return (Criteria) this;
		}

		public Criteria andInviteIsNull() {
			addCriterion("invite is null");
			return (Criteria) this;
		}

		public Criteria andInviteIsNotNull() {
			addCriterion("invite is not null");
			return (Criteria) this;
		}

		public Criteria andInviteEqualTo(Integer value) {
			addCriterion("invite =", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteNotEqualTo(Integer value) {
			addCriterion("invite <>", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteGreaterThan(Integer value) {
			addCriterion("invite >", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteGreaterThanOrEqualTo(Integer value) {
			addCriterion("invite >=", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteLessThan(Integer value) {
			addCriterion("invite <", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteLessThanOrEqualTo(Integer value) {
			addCriterion("invite <=", value, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteIn(List<Integer> values) {
			addCriterion("invite in", values, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteNotIn(List<Integer> values) {
			addCriterion("invite not in", values, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteBetween(Integer value1, Integer value2) {
			addCriterion("invite between", value1, value2, "invite");
			return (Criteria) this;
		}

		public Criteria andInviteNotBetween(Integer value1, Integer value2) {
			addCriterion("invite not between", value1, value2, "invite");
			return (Criteria) this;
		}

		public Criteria andInviterewardIsNull() {
			addCriterion("inviteReward is null");
			return (Criteria) this;
		}

		public Criteria andInviterewardIsNotNull() {
			addCriterion("inviteReward is not null");
			return (Criteria) this;
		}

		public Criteria andInviterewardEqualTo(Integer value) {
			addCriterion("inviteReward =", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardNotEqualTo(Integer value) {
			addCriterion("inviteReward <>", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardGreaterThan(Integer value) {
			addCriterion("inviteReward >", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardGreaterThanOrEqualTo(Integer value) {
			addCriterion("inviteReward >=", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardLessThan(Integer value) {
			addCriterion("inviteReward <", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardLessThanOrEqualTo(Integer value) {
			addCriterion("inviteReward <=", value, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardIn(List<Integer> values) {
			addCriterion("inviteReward in", values, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardNotIn(List<Integer> values) {
			addCriterion("inviteReward not in", values, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardBetween(Integer value1, Integer value2) {
			addCriterion("inviteReward between", value1, value2, "invitereward");
			return (Criteria) this;
		}

		public Criteria andInviterewardNotBetween(Integer value1, Integer value2) {
			addCriterion("inviteReward not between", value1, value2,
					"invitereward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardIsNull() {
			addCriterion("inviteGettedReward is null");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardIsNotNull() {
			addCriterion("inviteGettedReward is not null");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardEqualTo(Integer value) {
			addCriterion("inviteGettedReward =", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardNotEqualTo(Integer value) {
			addCriterion("inviteGettedReward <>", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardGreaterThan(Integer value) {
			addCriterion("inviteGettedReward >", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardGreaterThanOrEqualTo(Integer value) {
			addCriterion("inviteGettedReward >=", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardLessThan(Integer value) {
			addCriterion("inviteGettedReward <", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardLessThanOrEqualTo(Integer value) {
			addCriterion("inviteGettedReward <=", value, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardIn(List<Integer> values) {
			addCriterion("inviteGettedReward in", values, "invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardNotIn(List<Integer> values) {
			addCriterion("inviteGettedReward not in", values,
					"invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardBetween(Integer value1,
				Integer value2) {
			addCriterion("inviteGettedReward between", value1, value2,
					"invitegettedreward");
			return (Criteria) this;
		}

		public Criteria andInvitegettedrewardNotBetween(Integer value1,
				Integer value2) {
			addCriterion("inviteGettedReward not between", value1, value2,
					"invitegettedreward");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}