package com.dyz.myBatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoominfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roominfo
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roominfo
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table roominfo
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public RoominfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roominfo
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGametypeIsNull() {
			addCriterion("gameType is null");
			return (Criteria) this;
		}

		public Criteria andGametypeIsNotNull() {
			addCriterion("gameType is not null");
			return (Criteria) this;
		}

		public Criteria andGametypeEqualTo(String value) {
			addCriterion("gameType =", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeNotEqualTo(String value) {
			addCriterion("gameType <>", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeGreaterThan(String value) {
			addCriterion("gameType >", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeGreaterThanOrEqualTo(String value) {
			addCriterion("gameType >=", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeLessThan(String value) {
			addCriterion("gameType <", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeLessThanOrEqualTo(String value) {
			addCriterion("gameType <=", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeLike(String value) {
			addCriterion("gameType like", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeNotLike(String value) {
			addCriterion("gameType not like", value, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeIn(List<String> values) {
			addCriterion("gameType in", values, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeNotIn(List<String> values) {
			addCriterion("gameType not in", values, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeBetween(String value1, String value2) {
			addCriterion("gameType between", value1, value2, "gametype");
			return (Criteria) this;
		}

		public Criteria andGametypeNotBetween(String value1, String value2) {
			addCriterion("gameType not between", value1, value2, "gametype");
			return (Criteria) this;
		}

		public Criteria andIshongIsNull() {
			addCriterion("isHong is null");
			return (Criteria) this;
		}

		public Criteria andIshongIsNotNull() {
			addCriterion("isHong is not null");
			return (Criteria) this;
		}

		public Criteria andIshongEqualTo(String value) {
			addCriterion("isHong =", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongNotEqualTo(String value) {
			addCriterion("isHong <>", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongGreaterThan(String value) {
			addCriterion("isHong >", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongGreaterThanOrEqualTo(String value) {
			addCriterion("isHong >=", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongLessThan(String value) {
			addCriterion("isHong <", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongLessThanOrEqualTo(String value) {
			addCriterion("isHong <=", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongLike(String value) {
			addCriterion("isHong like", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongNotLike(String value) {
			addCriterion("isHong not like", value, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongIn(List<String> values) {
			addCriterion("isHong in", values, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongNotIn(List<String> values) {
			addCriterion("isHong not in", values, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongBetween(String value1, String value2) {
			addCriterion("isHong between", value1, value2, "ishong");
			return (Criteria) this;
		}

		public Criteria andIshongNotBetween(String value1, String value2) {
			addCriterion("isHong not between", value1, value2, "ishong");
			return (Criteria) this;
		}

		public Criteria andRoomidIsNull() {
			addCriterion("roomid is null");
			return (Criteria) this;
		}

		public Criteria andRoomidIsNotNull() {
			addCriterion("roomid is not null");
			return (Criteria) this;
		}

		public Criteria andRoomidEqualTo(Integer value) {
			addCriterion("roomid =", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotEqualTo(Integer value) {
			addCriterion("roomid <>", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidGreaterThan(Integer value) {
			addCriterion("roomid >", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidGreaterThanOrEqualTo(Integer value) {
			addCriterion("roomid >=", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidLessThan(Integer value) {
			addCriterion("roomid <", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidLessThanOrEqualTo(Integer value) {
			addCriterion("roomid <=", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidIn(List<Integer> values) {
			addCriterion("roomid in", values, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotIn(List<Integer> values) {
			addCriterion("roomid not in", values, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidBetween(Integer value1, Integer value2) {
			addCriterion("roomid between", value1, value2, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotBetween(Integer value1, Integer value2) {
			addCriterion("roomid not between", value1, value2, "roomid");
			return (Criteria) this;
		}

		public Criteria andSevendoubleIsNull() {
			addCriterion("sevenDouble is null");
			return (Criteria) this;
		}

		public Criteria andSevendoubleIsNotNull() {
			addCriterion("sevenDouble is not null");
			return (Criteria) this;
		}

		public Criteria andSevendoubleEqualTo(String value) {
			addCriterion("sevenDouble =", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleNotEqualTo(String value) {
			addCriterion("sevenDouble <>", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleGreaterThan(String value) {
			addCriterion("sevenDouble >", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleGreaterThanOrEqualTo(String value) {
			addCriterion("sevenDouble >=", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleLessThan(String value) {
			addCriterion("sevenDouble <", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleLessThanOrEqualTo(String value) {
			addCriterion("sevenDouble <=", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleLike(String value) {
			addCriterion("sevenDouble like", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleNotLike(String value) {
			addCriterion("sevenDouble not like", value, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleIn(List<String> values) {
			addCriterion("sevenDouble in", values, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleNotIn(List<String> values) {
			addCriterion("sevenDouble not in", values, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleBetween(String value1, String value2) {
			addCriterion("sevenDouble between", value1, value2, "sevendouble");
			return (Criteria) this;
		}

		public Criteria andSevendoubleNotBetween(String value1, String value2) {
			addCriterion("sevenDouble not between", value1, value2,
					"sevendouble");
			return (Criteria) this;
		}

		public Criteria andMaIsNull() {
			addCriterion("ma is null");
			return (Criteria) this;
		}

		public Criteria andMaIsNotNull() {
			addCriterion("ma is not null");
			return (Criteria) this;
		}

		public Criteria andMaEqualTo(Integer value) {
			addCriterion("ma =", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotEqualTo(Integer value) {
			addCriterion("ma <>", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaGreaterThan(Integer value) {
			addCriterion("ma >", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ma >=", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaLessThan(Integer value) {
			addCriterion("ma <", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaLessThanOrEqualTo(Integer value) {
			addCriterion("ma <=", value, "ma");
			return (Criteria) this;
		}

		public Criteria andMaIn(List<Integer> values) {
			addCriterion("ma in", values, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotIn(List<Integer> values) {
			addCriterion("ma not in", values, "ma");
			return (Criteria) this;
		}

		public Criteria andMaBetween(Integer value1, Integer value2) {
			addCriterion("ma between", value1, value2, "ma");
			return (Criteria) this;
		}

		public Criteria andMaNotBetween(Integer value1, Integer value2) {
			addCriterion("ma not between", value1, value2, "ma");
			return (Criteria) this;
		}

		public Criteria andZimoIsNull() {
			addCriterion("zimo is null");
			return (Criteria) this;
		}

		public Criteria andZimoIsNotNull() {
			addCriterion("zimo is not null");
			return (Criteria) this;
		}

		public Criteria andZimoEqualTo(String value) {
			addCriterion("zimo =", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoNotEqualTo(String value) {
			addCriterion("zimo <>", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoGreaterThan(String value) {
			addCriterion("zimo >", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoGreaterThanOrEqualTo(String value) {
			addCriterion("zimo >=", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoLessThan(String value) {
			addCriterion("zimo <", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoLessThanOrEqualTo(String value) {
			addCriterion("zimo <=", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoLike(String value) {
			addCriterion("zimo like", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoNotLike(String value) {
			addCriterion("zimo not like", value, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoIn(List<String> values) {
			addCriterion("zimo in", values, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoNotIn(List<String> values) {
			addCriterion("zimo not in", values, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoBetween(String value1, String value2) {
			addCriterion("zimo between", value1, value2, "zimo");
			return (Criteria) this;
		}

		public Criteria andZimoNotBetween(String value1, String value2) {
			addCriterion("zimo not between", value1, value2, "zimo");
			return (Criteria) this;
		}

		public Criteria andXiayuIsNull() {
			addCriterion("xiayu is null");
			return (Criteria) this;
		}

		public Criteria andXiayuIsNotNull() {
			addCriterion("xiayu is not null");
			return (Criteria) this;
		}

		public Criteria andXiayuEqualTo(Integer value) {
			addCriterion("xiayu =", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuNotEqualTo(Integer value) {
			addCriterion("xiayu <>", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuGreaterThan(Integer value) {
			addCriterion("xiayu >", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuGreaterThanOrEqualTo(Integer value) {
			addCriterion("xiayu >=", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuLessThan(Integer value) {
			addCriterion("xiayu <", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuLessThanOrEqualTo(Integer value) {
			addCriterion("xiayu <=", value, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuIn(List<Integer> values) {
			addCriterion("xiayu in", values, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuNotIn(List<Integer> values) {
			addCriterion("xiayu not in", values, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuBetween(Integer value1, Integer value2) {
			addCriterion("xiayu between", value1, value2, "xiayu");
			return (Criteria) this;
		}

		public Criteria andXiayuNotBetween(Integer value1, Integer value2) {
			addCriterion("xiayu not between", value1, value2, "xiayu");
			return (Criteria) this;
		}

		public Criteria andAddwordcardIsNull() {
			addCriterion("addWordCard is null");
			return (Criteria) this;
		}

		public Criteria andAddwordcardIsNotNull() {
			addCriterion("addWordCard is not null");
			return (Criteria) this;
		}

		public Criteria andAddwordcardEqualTo(String value) {
			addCriterion("addWordCard =", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardNotEqualTo(String value) {
			addCriterion("addWordCard <>", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardGreaterThan(String value) {
			addCriterion("addWordCard >", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardGreaterThanOrEqualTo(String value) {
			addCriterion("addWordCard >=", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardLessThan(String value) {
			addCriterion("addWordCard <", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardLessThanOrEqualTo(String value) {
			addCriterion("addWordCard <=", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardLike(String value) {
			addCriterion("addWordCard like", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardNotLike(String value) {
			addCriterion("addWordCard not like", value, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardIn(List<String> values) {
			addCriterion("addWordCard in", values, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardNotIn(List<String> values) {
			addCriterion("addWordCard not in", values, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardBetween(String value1, String value2) {
			addCriterion("addWordCard between", value1, value2, "addwordcard");
			return (Criteria) this;
		}

		public Criteria andAddwordcardNotBetween(String value1, String value2) {
			addCriterion("addWordCard not between", value1, value2,
					"addwordcard");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCardnumbIsNull() {
			addCriterion("cardNumb is null");
			return (Criteria) this;
		}

		public Criteria andCardnumbIsNotNull() {
			addCriterion("cardNumb is not null");
			return (Criteria) this;
		}

		public Criteria andCardnumbEqualTo(Integer value) {
			addCriterion("cardNumb =", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbNotEqualTo(Integer value) {
			addCriterion("cardNumb <>", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbGreaterThan(Integer value) {
			addCriterion("cardNumb >", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbGreaterThanOrEqualTo(Integer value) {
			addCriterion("cardNumb >=", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbLessThan(Integer value) {
			addCriterion("cardNumb <", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbLessThanOrEqualTo(Integer value) {
			addCriterion("cardNumb <=", value, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbIn(List<Integer> values) {
			addCriterion("cardNumb in", values, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbNotIn(List<Integer> values) {
			addCriterion("cardNumb not in", values, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbBetween(Integer value1, Integer value2) {
			addCriterion("cardNumb between", value1, value2, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andCardnumbNotBetween(Integer value1, Integer value2) {
			addCriterion("cardNumb not between", value1, value2, "cardnumb");
			return (Criteria) this;
		}

		public Criteria andTotalplayersIsNull() {
			addCriterion("totalPlayers is null");
			return (Criteria) this;
		}

		public Criteria andTotalplayersIsNotNull() {
			addCriterion("totalPlayers is not null");
			return (Criteria) this;
		}

		public Criteria andTotalplayersEqualTo(Integer value) {
			addCriterion("totalPlayers =", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersNotEqualTo(Integer value) {
			addCriterion("totalPlayers <>", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersGreaterThan(Integer value) {
			addCriterion("totalPlayers >", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersGreaterThanOrEqualTo(Integer value) {
			addCriterion("totalPlayers >=", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersLessThan(Integer value) {
			addCriterion("totalPlayers <", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersLessThanOrEqualTo(Integer value) {
			addCriterion("totalPlayers <=", value, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersIn(List<Integer> values) {
			addCriterion("totalPlayers in", values, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersNotIn(List<Integer> values) {
			addCriterion("totalPlayers not in", values, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersBetween(Integer value1, Integer value2) {
			addCriterion("totalPlayers between", value1, value2, "totalplayers");
			return (Criteria) this;
		}

		public Criteria andTotalplayersNotBetween(Integer value1, Integer value2) {
			addCriterion("totalPlayers not between", value1, value2,
					"totalplayers");
			return (Criteria) this;
		}

		public Criteria andShengyu20IsNull() {
			addCriterion("shengyu20 is null");
			return (Criteria) this;
		}

		public Criteria andShengyu20IsNotNull() {
			addCriterion("shengyu20 is not null");
			return (Criteria) this;
		}

		public Criteria andShengyu20EqualTo(String value) {
			addCriterion("shengyu20 =", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20NotEqualTo(String value) {
			addCriterion("shengyu20 <>", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20GreaterThan(String value) {
			addCriterion("shengyu20 >", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20GreaterThanOrEqualTo(String value) {
			addCriterion("shengyu20 >=", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20LessThan(String value) {
			addCriterion("shengyu20 <", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20LessThanOrEqualTo(String value) {
			addCriterion("shengyu20 <=", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20Like(String value) {
			addCriterion("shengyu20 like", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20NotLike(String value) {
			addCriterion("shengyu20 not like", value, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20In(List<String> values) {
			addCriterion("shengyu20 in", values, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20NotIn(List<String> values) {
			addCriterion("shengyu20 not in", values, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20Between(String value1, String value2) {
			addCriterion("shengyu20 between", value1, value2, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andShengyu20NotBetween(String value1, String value2) {
			addCriterion("shengyu20 not between", value1, value2, "shengyu20");
			return (Criteria) this;
		}

		public Criteria andThreefornextIsNull() {
			addCriterion("threefornext is null");
			return (Criteria) this;
		}

		public Criteria andThreefornextIsNotNull() {
			addCriterion("threefornext is not null");
			return (Criteria) this;
		}

		public Criteria andThreefornextEqualTo(String value) {
			addCriterion("threefornext =", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextNotEqualTo(String value) {
			addCriterion("threefornext <>", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextGreaterThan(String value) {
			addCriterion("threefornext >", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextGreaterThanOrEqualTo(String value) {
			addCriterion("threefornext >=", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextLessThan(String value) {
			addCriterion("threefornext <", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextLessThanOrEqualTo(String value) {
			addCriterion("threefornext <=", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextLike(String value) {
			addCriterion("threefornext like", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextNotLike(String value) {
			addCriterion("threefornext not like", value, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextIn(List<String> values) {
			addCriterion("threefornext in", values, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextNotIn(List<String> values) {
			addCriterion("threefornext not in", values, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextBetween(String value1, String value2) {
			addCriterion("threefornext between", value1, value2, "threefornext");
			return (Criteria) this;
		}

		public Criteria andThreefornextNotBetween(String value1, String value2) {
			addCriterion("threefornext not between", value1, value2,
					"threefornext");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiIsNull() {
			addCriterion("showTingPai is null");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiIsNotNull() {
			addCriterion("showTingPai is not null");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiEqualTo(String value) {
			addCriterion("showTingPai =", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiNotEqualTo(String value) {
			addCriterion("showTingPai <>", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiGreaterThan(String value) {
			addCriterion("showTingPai >", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiGreaterThanOrEqualTo(String value) {
			addCriterion("showTingPai >=", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiLessThan(String value) {
			addCriterion("showTingPai <", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiLessThanOrEqualTo(String value) {
			addCriterion("showTingPai <=", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiLike(String value) {
			addCriterion("showTingPai like", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiNotLike(String value) {
			addCriterion("showTingPai not like", value, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiIn(List<String> values) {
			addCriterion("showTingPai in", values, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiNotIn(List<String> values) {
			addCriterion("showTingPai not in", values, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiBetween(String value1, String value2) {
			addCriterion("showTingPai between", value1, value2, "showtingpai");
			return (Criteria) this;
		}

		public Criteria andShowtingpaiNotBetween(String value1, String value2) {
			addCriterion("showTingPai not between", value1, value2,
					"showtingpai");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table roominfo
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table roominfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}