package com.dyz.myBatis.model;

import java.util.Date;

public class Roominfo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.id
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.gameType
	 * @mbggenerated
	 */
	private String gametype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.isHong
	 * @mbggenerated
	 */
	private String ishong;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.roomid
	 * @mbggenerated
	 */
	private Integer roomid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.sevenDouble
	 * @mbggenerated
	 */
	private String sevendouble;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.ma
	 * @mbggenerated
	 */
	private Integer ma;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.zimo
	 * @mbggenerated
	 */
	private String zimo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.xiayu
	 * @mbggenerated
	 */
	private Integer xiayu;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.addWordCard
	 * @mbggenerated
	 */
	private String addwordcard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.createTime
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.cardNumb
	 * @mbggenerated
	 */
	private Integer cardnumb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.totalPlayers
	 * @mbggenerated
	 */
	private Integer totalplayers;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.shengyu20
	 * @mbggenerated
	 */
	private String shengyu20;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.threefornext
	 * @mbggenerated
	 */
	private String threefornext;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roominfo.showTingPai
	 * @mbggenerated
	 */
	private String showtingpai;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.id
	 * @return  the value of roominfo.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.id
	 * @param id  the value for roominfo.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.gameType
	 * @return  the value of roominfo.gameType
	 * @mbggenerated
	 */
	public String getGametype() {
		return gametype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.gameType
	 * @param gametype  the value for roominfo.gameType
	 * @mbggenerated
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype == null ? null : gametype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.isHong
	 * @return  the value of roominfo.isHong
	 * @mbggenerated
	 */
	public String getIshong() {
		return ishong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.isHong
	 * @param ishong  the value for roominfo.isHong
	 * @mbggenerated
	 */
	public void setIshong(String ishong) {
		this.ishong = ishong == null ? null : ishong.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.roomid
	 * @return  the value of roominfo.roomid
	 * @mbggenerated
	 */
	public Integer getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.roomid
	 * @param roomid  the value for roominfo.roomid
	 * @mbggenerated
	 */
	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.sevenDouble
	 * @return  the value of roominfo.sevenDouble
	 * @mbggenerated
	 */
	public String getSevendouble() {
		return sevendouble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.sevenDouble
	 * @param sevendouble  the value for roominfo.sevenDouble
	 * @mbggenerated
	 */
	public void setSevendouble(String sevendouble) {
		this.sevendouble = sevendouble == null ? null : sevendouble.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.ma
	 * @return  the value of roominfo.ma
	 * @mbggenerated
	 */
	public Integer getMa() {
		return ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.ma
	 * @param ma  the value for roominfo.ma
	 * @mbggenerated
	 */
	public void setMa(Integer ma) {
		this.ma = ma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.zimo
	 * @return  the value of roominfo.zimo
	 * @mbggenerated
	 */
	public String getZimo() {
		return zimo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.zimo
	 * @param zimo  the value for roominfo.zimo
	 * @mbggenerated
	 */
	public void setZimo(String zimo) {
		this.zimo = zimo == null ? null : zimo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.xiayu
	 * @return  the value of roominfo.xiayu
	 * @mbggenerated
	 */
	public Integer getXiayu() {
		return xiayu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.xiayu
	 * @param xiayu  the value for roominfo.xiayu
	 * @mbggenerated
	 */
	public void setXiayu(Integer xiayu) {
		this.xiayu = xiayu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.addWordCard
	 * @return  the value of roominfo.addWordCard
	 * @mbggenerated
	 */
	public String getAddwordcard() {
		return addwordcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.addWordCard
	 * @param addwordcard  the value for roominfo.addWordCard
	 * @mbggenerated
	 */
	public void setAddwordcard(String addwordcard) {
		this.addwordcard = addwordcard == null ? null : addwordcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.name
	 * @return  the value of roominfo.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.name
	 * @param name  the value for roominfo.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.createTime
	 * @return  the value of roominfo.createTime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.createTime
	 * @param createtime  the value for roominfo.createTime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.cardNumb
	 * @return  the value of roominfo.cardNumb
	 * @mbggenerated
	 */
	public Integer getCardnumb() {
		return cardnumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.cardNumb
	 * @param cardnumb  the value for roominfo.cardNumb
	 * @mbggenerated
	 */
	public void setCardnumb(Integer cardnumb) {
		this.cardnumb = cardnumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.totalPlayers
	 * @return  the value of roominfo.totalPlayers
	 * @mbggenerated
	 */
	public Integer getTotalplayers() {
		return totalplayers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.totalPlayers
	 * @param totalplayers  the value for roominfo.totalPlayers
	 * @mbggenerated
	 */
	public void setTotalplayers(Integer totalplayers) {
		this.totalplayers = totalplayers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.shengyu20
	 * @return  the value of roominfo.shengyu20
	 * @mbggenerated
	 */
	public String getShengyu20() {
		return shengyu20;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.shengyu20
	 * @param shengyu20  the value for roominfo.shengyu20
	 * @mbggenerated
	 */
	public void setShengyu20(String shengyu20) {
		this.shengyu20 = shengyu20 == null ? null : shengyu20.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.threefornext
	 * @return  the value of roominfo.threefornext
	 * @mbggenerated
	 */
	public String getThreefornext() {
		return threefornext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.threefornext
	 * @param threefornext  the value for roominfo.threefornext
	 * @mbggenerated
	 */
	public void setThreefornext(String threefornext) {
		this.threefornext = threefornext == null ? null : threefornext.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roominfo.showTingPai
	 * @return  the value of roominfo.showTingPai
	 * @mbggenerated
	 */
	public String getShowtingpai() {
		return showtingpai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roominfo.showTingPai
	 * @param showtingpai  the value for roominfo.showTingPai
	 * @mbggenerated
	 */
	public void setShowtingpai(String showtingpai) {
		this.showtingpai = showtingpai == null ? null : showtingpai.trim();
	}
    
}